apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-disable-self-provisioner
placementRef:
  name: placement-policy-disable-self-provisioner
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: policy-disable-self-provisioner
    apiGroup: policy.open-cluster-management.io
    kind: Policy
