apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-disable-self-provisioner
spec:
  clusterSelector:
    matchExpressions:
      - key: environment
        operator: In
        values:
          - prod
