bases:
  - ../base
patchesJson6902:
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRoleBinding
      name: self-provisioners
    path: self-provisioners-clusterrolebinding.yaml
